site_name: Kelpie-Carbon
theme:
  name: material
nav:
  - Home: index.md
  - Roadmap: ROADMAP.md
  - Architecture: ARCHITECTURE.md
  - API: API_REFERENCE.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

exclude_docs: |
  ARCHIVE/
