site_name: Kelpie-Carbon
site_url: https://illidus.github.io/kelpie-carbon-v1/docs/
site_dir: site/docs
theme:
  name: material
nav:
  - Home: index.md
  - Roadmap: ROADMAP.md
  - Architecture: ARCHITECTURE.md
  - API: API_REFERENCE.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

exclude_docs: |
  ARCHIVE/
