# Kelpie Carbon v1 - Production Configuration
# Configuration file for production deployment

app:
  name: "Kelpie Carbon v1"
  version: "1.0.0"
  environment: "production"
  debug: false
  description: "Kelp Forest Carbon Sequestration Assessment"

server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4
  access_log: false
  log_level: "info"
  worker_class: "uvicorn.workers.UvicornWorker"
  max_requests: 1000
  max_requests_jitter: 100
  keepalive: 2

# Data processing configuration
processing:
  max_concurrent_analyses: 20
  analysis_timeout: 600  # seconds
  image_cache_size: 1000
  image_cache_ttl: 7200  # seconds (2 hours)

# Satellite data configuration
satellite:
  data_source: "microsoft_planetary_computer"
  max_cloud_cover: 0.2  # 20% (stricter for production)
  preferred_resolution: 10  # meters
  max_scenes_per_request: 10
  timeout: 60  # seconds
  retry_attempts: 3
  retry_delay: 5  # seconds

# Machine learning configuration
ml_models:
  kelp_detection:
    model_type: "random_forest"
    confidence_threshold: 0.75  # Higher confidence for production
    min_area_threshold: 50  # square meters
    preprocessing:
      normalize: true
      remove_outliers: true
  
  biomass_estimation:
    model_type: "regression"
    units: "tons_per_hectare"
    carbon_conversion_factor: 0.45
    uncertainty_estimation: true

# Image generation settings
image_generation:
  rgb_composite:
    format: "JPEG"
    quality: 80  # Optimized for size vs quality
    enhancement: true
    progressive: true
    
  spectral_indices:
    format: "PNG"
    colormap: "viridis"
    transparency: true
    compression_level: 6
    
  overlays:
    format: "PNG"
    default_alpha: 0.6
    line_width: 1
    anti_aliasing: true

# Performance and caching
cache:
  type: "redis"  # Use Redis for production
  redis_url: "${REDIS_URL}"
  max_size: "5GB"
  cleanup_interval: 1800  # seconds (30 minutes)
  compression: true
  compression_level: 6

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  include_timestamp: true
  include_module: false
  console_output: true
  file_output: true
  log_file: "/var/log/kelpie/app.log"
  rotation:
    max_size: "100MB"
    backup_count: 10

# CORS configuration for production
cors:
  allow_origins:
    - "https://kelpie.your-domain.com"
    - "https://www.your-domain.com"
  allow_credentials: true
  allow_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allow_headers:
    - "Content-Type"
    - "Authorization"
    - "Accept"
    - "Origin"
    - "X-Requested-With"

# Security settings
security:
  trusted_hosts:
    - "kelpie.your-domain.com"
    - "your-domain.com"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 100
  
  headers:
    hsts_max_age: 31536000  # 1 year
    content_type_nosniff: true
    frame_options: "DENY"
    xss_protection: "1; mode=block"
  
  ssl:
    redirect_https: true
    ssl_version: "TLSv1.2"

# Database configuration (future enhancement)
database:
  enabled: true
  url: "${DATABASE_URL}"
  echo: false
  pool_size: 20
  max_overflow: 30
  pool_pre_ping: true
  pool_recycle: 3600

# External services
external_services:
  planetary_computer:
    base_url: "https://planetarycomputer.microsoft.com"
    timeout: 60
    retry_attempts: 3
    retry_delay: 5
    
  sentry:
    enabled: true
    dsn: "${SENTRY_DSN}"
    environment: "production"
    traces_sample_rate: 0.1
    
  monitoring:
    prometheus:
      enabled: true
      port: 9090
      path: "/metrics"
    
    grafana:
      enabled: true
      dashboard_url: "${GRAFANA_URL}"

# Feature flags
features:
  enable_performance_monitoring: true
  enable_progressive_loading: true
  enable_error_recovery: true
  enable_cache_optimization: true
  enable_real_time_updates: true
  enable_analytics: true

# Production optimizations
production:
  preload_models: true
  warm_cache: true
  optimize_images: true
  enable_compression: true
  static_file_cache: true

# Monitoring and metrics
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"
  readiness_check_endpoint: "/ready"
  
  alerts:
    high_memory_usage: 0.85
    high_cpu_usage: 0.80
    high_error_rate: 0.05
    slow_response_time: 5.0  # seconds
  
  retention:
    metrics: "30d"
    logs: "90d"
    traces: "7d"

# File paths
paths:
  static_files: "/app/static"
  templates: "/app/templates"
  logs: "/var/log/kelpie"
  cache: "/var/cache/kelpie"
  temp: "/tmp/kelpie"

# Backup and recovery
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: "30d"
  destination: "${BACKUP_DESTINATION}"
  
  includes:
    - "/var/log/kelpie"
    - "/etc/kelpie"
  
  excludes:
    - "/tmp"
    - "/var/cache"

# Auto-scaling configuration
autoscaling:
  enabled: true
  min_instances: 2
  max_instances: 10
  target_cpu_utilization: 70
  target_memory_utilization: 80
  scale_up_cooldown: 300  # seconds
  scale_down_cooldown: 600  # seconds

# Load balancing
load_balancer:
  health_check_path: "/health"
  health_check_interval: 30  # seconds
  healthy_threshold: 2
  unhealthy_threshold: 3
  timeout: 5  # seconds

# Environment variables
environment:
  SECRET_KEY: "${SECRET_KEY}"
  DATABASE_URL: "${DATABASE_URL}"
  REDIS_URL: "${REDIS_URL}"
  SENTRY_DSN: "${SENTRY_DSN}"
  PLANETARY_COMPUTER_KEY: "${PLANETARY_COMPUTER_KEY}" 