name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fast-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache pytest cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pytest
          key: ${{ runner.os }}-pytest-${{ hashFiles('**/pytest.ini', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pytest-

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run pre-commit on all files
        run: poetry run pre-commit run --all-files

      - name: Run tests
        run: poetry run pytest -n auto -m "not slow"

  docs-build:
    runs-on: ubuntu-latest
    needs: fast-check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build docs
        run: poetry run mkdocs build --strict

  pages-deploy:
    needs: docs-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - name: Upload docs to gh-pages/docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/docs
      - name: Deploy
        uses: actions/deploy-pages@v4
